# Generated by Django 4.1.4 on 2022-12-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='date',
            field=models.DateField(default='2022-12-25'),
            preserve_default=False,
        ),
    ]
